# Generated by Django 4.0 on 2022-07-19 20:41

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CJO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quillpost',
            name='content',
            field=django_quill.fields.QuillField(unique=True),
        ),
    ]
