# Generated by Django 4.0 on 2022-07-19 20:49

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CJO', '0002_alter_quillpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quillpost',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
