# Generated by Django 4.0 on 2022-12-12 15:14

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CJO', '0003_alter_quillpost_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadImage', models.ImageField(upload_to='files/leadImages')),
                ('headLine', models.CharField(max_length=300)),
                ('content', django_quill.fields.QuillField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CJO.category')),
            ],
        ),
        migrations.DeleteModel(
            name='QuillPost',
        ),
    ]
