# Generated by Django 4.0 on 2022-12-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CJO', '0004_category_newsarticle_delete_quillpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
